apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
  labels: {}
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      version: 6.5.3
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m0s
  releaseName: podinfo
  uninstall:
    keepHistory: false
  values: {}
  valuesFrom: []
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          version: v1
          kind: Deployment
          name: podinfo
          namespace: podinfo
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: podinfo
        - op: add
          path: /spec/template/metadata/labels/environment
          value: development
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
      - target:
          version: v1
          kind: Deployment
          name: prometheus-server
          namespace: podinfo
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: podinfo
        - op: add
          path: /spec/template/metadata/labels/environment
          value: development
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
      - target:
          version: v1
          kind: Deployment
          name: prometheus-prometheus-pushgateway
          namespace: podinfo
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: podinfo
        - op: add
          path: /spec/template/metadata/labels/environment
          value: development
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
      - target:
          version: v1
          kind: Deployment
          name: prometheus-kube-state-metrics
          namespace: podinfo
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: podinfo
        - op: add
          path: /spec/template/metadata/labels/environment
          value: development
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
