apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
    environment: development
    owner: sanujan
    project: advanto
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      version: 15.4.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: nginx
  uninstall:
    keephistory: false
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: nginx
          labels:
            labels:
              app: nginx
              environment: development
              owner: sanujan
              project: advanto
        spec:
          selector:
            matchLabels:
              labels:
                app: nginx
                environment: development
                owner: sanujan
                project: advanto
          template:
            metadata:
              labels:
                app: nginx
                environment: development
                owner: sanujan
                project: advanto
