apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: argocd
spec:
  chart:
    spec:
      chart: argo-cd
      reconcileStrategy: ChartVersion
      version: 5.51.6
      sourceRef:
        kind: HelmRepository
        name: argo
  interval: 5m0s
  releaseName: argo-cd
  values: {}
  valuesFrom: []
