apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      version: 55.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 5m0s
  releaseName: kube-prometheus-stack
  values: {}
  valuesFrom: []
