apiVersion: v1
data:
  identity: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQW1LVktSSWZ5SXdEMmxkRG4KWFlzWGVBZDFuOENwYVlJMCtsTDdiNC9Hc0FWVUtPZk1UdTlyKzhYUnpnZ21TRHg5SzZhWms5bVd4QU5zQlBGVwpLUUlvSE9haGdZa0RnWVlBQkFBTTFUclArdFBKTkxZNU4zMFBlb2VHZmtER1BxUFo4Mm56TjBMSGZvZ2ZEbnZyCllBL1g0UmoyRFhVKzZlWC9aUm9YOU5Vczlwd0prTE9mVU1DRWJxc3J4UUJ0UUNnRk4rY0JNazg5K3pzSjdLUFQKOHI3R2owNFU4Qmova3hPUVVJS3g3RXhYV2MwbWM3T2lZUDlSNWRMdTVhbE1oSzhUSzN6RXV4L3B4TzU5eXAxeApGUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  identity.pub: ZWNkc2Etc2hhMi1uaXN0cDUyMSBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEExTWpFQUFBQUlibWx6ZEhBMU1qRUFBQUNGQkFBTTFUclArdFBKTkxZNU4zMFBlb2VHZmtER1BxUFo4Mm56TjBMSGZvZ2ZEbnZyWUEvWDRSajJEWFUrNmVYL1pSb1g5TlVzOXB3SmtMT2ZVTUNFYnFzcnhRQnRRQ2dGTitjQk1rODkrenNKN0tQVDhyN0dqMDRVOEJqL2t4T1FVSUt4N0V4WFdjMG1jN09pWVA5UjVkTHU1YWxNaEs4VEszekV1eC9weE81OXlwMXhGUT09Cg==
  known_hosts: Z2l0aHViLmNvbSBlY2RzYS1zaGEyLW5pc3RwMjU2IEFBQUFFMlZqWkhOaExYTm9ZVEl0Ym1semRIQXlOVFlBQUFBSWJtbHpkSEF5TlRZQUFBQkJCRW1LU0VOalFFZXpPbXhrWk15N29wS2d3RkI5bmt0NVlScllNak51RzVOODd1UmdnNkNMcmJvNXdBZFQveTZ2MG1LVjBVMncwV1oyWUIvKytUcG9ja2c9
kind: Secret
metadata:
  creationTimestamp: "2023-09-06T05:06:40Z"
  name: flux-system
  namespace: flux-system
  resourceVersion: "932"
  uid: 1c07e83d-00b9-4357-b4e7-46b070490535
type: Opaque
