apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      version: 25.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 5m0s
  releaseName: prometheus
  uninstall:
    keepHistory: false
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          version: v1
          kind: Deployment
          name: prometheus
          namespace: default
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: prometheus
        - op: add
          path: /spec/template/metadata/labels/organization-id
          value: org_ba1b5bee-af4f-45d1-a664-6c3de84ae72c
        - op: add
          path: /spec/template/metadata/labels/project-id
          value: project_7d6a36ec-4ee2-4dab-8ed4-21cdbac946f2
        - op: add
          path: /spec/template/metadata/labels/cluster-id
          value: cluster_91e4457c-8e18-4cb3-a9cf-20984810e7b5
        - op: add
          path: /spec/template/metadata/labels/release-id
          value: 10
