apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      version: 15.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: nginx
  values: {}
  valuesFrom: []
