apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
    environment: production
    owner: sanujan
    project: skyu
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      version: 15.4.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: nginx
  uninstall:
    keepHistory: false
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: nginx
          namespace: default
          labels:
            app: nginx
            environment: production
            owner: sanujan
            project: skyu
        spec:
          selector:
            matchLabels:
              app: nginx
              environment: production
              owner: sanujan
              project: skyu
          template:
            metadata:
              labels:
                app: nginx
                environment: production
                owner: sanujan
                project: skyu
