apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
  labels: {}
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      version: 15.4.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: nginx
  uninstall:
    keepHistory: false
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          version: v1
          kind: Deployment
          name: nginx
          namespace: default
        patch:
        - op: add
          path: /spec/template/metadata/labels/environment
          value: pro
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
