apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: default
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      version: 1.13.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 5m0s
  releaseName: cert-manager
  values: {}
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-configmap
    valuesKey: replicaCount
    targetPath: replicaCount
  - kind: ConfigMap
    name: cert-manager-configmap
    valuesKey: global.priorityClassName
    targetPath: global.priorityClassName
  - kind: ConfigMap
    name: cert-manager-configmap
    valuesKey: installCRDs
    targetPath: installCRDs
