apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: default
data:
  alertmanager.enabled: "false"
  prometheus-pushgateway.enabled: "false"
  server.global.scrape_interval: 30s
  server.ingress.enabled: "true"
  server.persistentVolume.enabled: "false"
  server.priorityClassName: infra-high-priority
  server.service.servicePort: "9090"
  server.statefulSet.enabled: "false"
  serviceAccounts.server.name: amp-iamproxy-ingest-service-account
