apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      version: 25.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 5m0s
  releaseName: prometheus
  values:
    affinity: {}
    backend: null
    backends: []
    cache: ""
    certificate:
      create: false
      dnsNames:
      - podinfo
      issuerRef:
        kind: ClusterIssuer
        name: self-signed
    faults:
      delay: false
      error: false
      testFail: false
      testTimeout: false
      unhealthy: false
      unready: false
    h2c:
      enabled: false
    host: null
    hpa:
      cpu: null
      enabled: false
      maxReplicas: 10
      memory: null
      requests: null
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/stefanprodan/podinfo
      tag: 6.5.3
    ingress:
      additionalLabels: {}
      annotations: {}
      className: ""
      enabled: false
      hosts:
      - host: podinfo.local
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls: []
    linkerd:
      profile:
        enabled: false
    logLevel: info
    nodeSelector: {}
    podAnnotations: {}
    probes:
      liveness:
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readiness:
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      startup:
        enable: false
        failureThreshold: 20
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
    redis:
      enabled: false
      repository: redis
      tag: 7.0.7
    replicaCount: 1
    resources:
      limits: null
      requests:
        cpu: 1m
        memory: 16Mi
    securityContext: {}
    service:
      annotations: {}
      enabled: true
      externalPort: 9898
      grpcPort: 9999
      grpcService: podinfo
      hostPort: null
      httpPort: 9898
      metricsPort: 9797
      nodePort: 31198
      type: ClusterIP
    serviceAccount:
      enabled: false
      imagePullSecrets: []
      name: null
    serviceAccounts:
      server:
        annotations:
          eks.amazonaws.com/role-arn: ""
    serviceMonitor:
      additionalLabels: {}
      enabled: false
      interval: 15s
    tls:
      certPath: /data/cert
      enabled: false
      hostPort: null
      port: 9899
      secretName: null
    tolerations: []
    ui:
      color: '#34577c'
      logo: ""
      message: ""
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: serviceAccounts.server.name
    targetPath: serviceAccounts.server.name
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: prometheus-pushgateway.enabled
    targetPath: prometheus-pushgateway.enabled
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: alertmanager.enabled
    targetPath: alertmanager.enabled
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: server.priorityClassName
    targetPath: server.priorityClassName
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: server.ingress.enabled
    targetPath: server.ingress.enabled
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: server.persistentVolume.enabled
    targetPath: server.persistentVolume.enabled
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: server.global.scrape_interval
    targetPath: server.global.scrape_interval
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: server.statefulSet.enabled
    targetPath: server.statefulSet.enabled
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: server.service.servicePort
    targetPath: server.service.servicePort
  - kind: ConfigMap
    name: prometheus-configmap
    valuesKey: server.service.servicePort
    targetPath: server.service.servicePort
