apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      version: 4.8.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 5m0s
  releaseName: ingress-nginx
  values: {}
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-configmap
    valuesKey: controller.metrics.service.annotations.prometheus.io_port
    targetPath: controller.metrics.service.annotations.prometheus.io_port
  - kind: ConfigMap
    name: ingress-nginx-configmap
    valuesKey: controller.metrics.service.annotations.prometheus.io_scrape
    targetPath: controller.metrics.service.annotations.prometheus.io_scrape
