apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-configmap
  namespace: default
data:
  controller.autoscaling.enabled: true
  controller.autoscaling.maxReplicas: 10
  controller.autoscaling.minReplicas: 2
  controller.autoscaling.targetCPUUtilizationPercentage: 75
  controller.config.client-body-buffer-size: 8m
  controller.ingressClassResource.name: nginx-private
  controller.metrics.enabled: "2"
  controller.metrics.service.annotations.prometheus.io_port: "10254"
  controller.metrics.service.annotations.prometheus.io_scrape: true
  controller.minAvailable: "1"
  controller.replicaCount: "2"
  controller.resources.limits.cpu: 1000m
  controller.resources.limits.memory: 2Gi
  controller.resources.requests.cpu: 100m
  controller.resources.requests.memory: 250Mi
  controller.service.annotations.service.beta.kubernetes.io_aws-load-balancer-cross-zone-load-balancing-enabled: true
  controller.service.annotations.service.beta.kubernetes.io_aws-load-balancer-internal: false
  controller.service.annotations.service.beta.kubernetes.io_aws-load-balancer-name: nlb-helm-test-cluster
  controller.service.annotations.service.beta.kubernetes.io_aws-load-balancer-type: nlb
  controller.service.internal.enabled: true
