name: "nginx"
packagename: "nginx"
sourcerefname: "bitnami"
hemlrepositoryurl: "https://grafana.github.io/helm-charts"
version: "7.0.3"
valuesfrom:
  - overwritepath: "replicaCount"
    value: "2"
  - overwritepath: "service.type"
    value: "LoadBalancer"
  - overwritepath: "service.port"
    value: "81"
  - overwritepath: "readinessProbe.httpGet.port"
    value: "3001"
