name: "nginx"
version: "7.0.3"
repository:
  sourcerefname: "bitnami"
  url: "https://grafana.github.io/helm-charts"
valuesfrom:
  - overwritepath: "replicaCount"
    value: "2"
  - overwritepath: "service.type"
    value: "LoadBalancer"
  - overwritepath: "service.port"
    value: "81"
  - overwritepath: "readinessProbe.httpGet.port"
    value: "3001"
