apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      version: 6.5.3
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m0s
  releaseName: podinfo
  uninstall:
    keepHistory: false
  values:
    controller:
      metrics:
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-internal: "false"
          service.beta.kubernetes.io/aws-load-balancer-name: nlb-helm-test-cluster
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
  valuesFrom:
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  - kind: ""
    name: ""
    valuesKey: ""
    targetPath: ""
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          version: v1
          kind: Deployment
          name: podinfo
          namespace: default
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: podinfo
        - op: add
          path: /spec/template/metadata/labels/environment
          value: development
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
