apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      version: 6.1.5
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m0s
  releaseName: podinfo
  uninstall:
    keepHistory: false
  values:
    affinity: {}
    backend: null
    backends: []
    cache: ""
    certificate:
      create: false
      dnsNames:
      - podinfo
      issuerRef:
        kind: ClusterIssuer
        name: self-signed
    faults:
      delay: false
      error: false
      testFail: false
      testTimeout: false
      unhealthy: false
      unready: false
    h2c:
      enabled: false
    host: null
    hpa:
      cpu: null
      enabled: false
      maxReplicas: 10
      memory: null
      requests: null
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/stefanprodan/podinfo
      tag: 6.5.3
    ingress:
      additionalLabels: {}
      annotations: {}
      className: ""
      enabled: false
      hosts:
      - host: podinfo.local
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls: []
    linkerd:
      profile:
        enabled: false
    logLevel: info
    nodeSelector: {}
    podAnnotations: {}
    probes:
      liveness:
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readiness:
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      startup:
        enable: false
        failureThreshold: 20
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
    redis:
      enabled: false
      repository: redis
      tag: 7.0.7
    replicaCount: 1
    resources:
      limits: null
      requests:
        cpu: 1m
        memory: 16Mi
    securityContext: {}
    service:
      annotations: {}
      enabled: true
      externalPort: 9898
      grpcPort: 9999
      grpcService: podinfo
      hostPort: null
      httpPort: 9898
      metricsPort: 9797
      nodePort: 31198
      type: ClusterIP
    serviceAccount:
      enabled: false
      imagePullSecrets: []
      name: null
    serviceMonitor:
      additionalLabels: {}
      enabled: false
      interval: 15s
    tls:
      certPath: /data/cert
      enabled: false
      hostPort: null
      port: 9899
      secretName: null
    tolerations: []
    ui:
      color: '#34577c'
      logo: ""
      message: ""
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          version: v1
          kind: Deployment
          name: podinfo
          namespace: default
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: podinfo
        - op: add
          path: /spec/template/metadata/labels/organization-id
          value: org_ba1b5bee-af4f-45d1-a664-6c3de84ae72c
        - op: add
          path: /spec/template/metadata/labels/project-id
          value: project_7d6a36ec-4ee2-4dab-8ed4-21cdbac946f2
        - op: add
          path: /spec/template/metadata/labels/cluster-id
          value: cluster_91e4457c-8e18-4cb3-a9cf-20984810e7b5
        - op: add
          path: /spec/template/metadata/labels/release-id
          value: "10"
