apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
  labels:
    app.kubernetes.io/name: prometheus
    environment: pro
    owner: sanujan
    project: advanto
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      version: 25.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 5m0s
  releaseName: prometheus
  uninstall:
    keepHistory: false
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: prometheus
          namespace: default
          labels:
            app.kubernetes.io/name: prometheus
            environment: pro
            owner: sanujan
            project: advanto
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus
              environment: pro
              owner: sanujan
              project: advanto
          template:
            metadata:
              labels:
                app.kubernetes.io/name: prometheus
                environment: pro
                owner: sanujan
                project: advanto
