apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
  labels:
    app: prometheus
    environment: development
    owner: naruto
    project: conveyancer
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      version: 25.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 5m0s
  releaseName: prometheus
  uninstall:
    keepHistory: false
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: prometheus
          namespace: default
          labels:
            app: prometheus
            environment: development
            owner: naruto
            project: conveyancer
        spec:
          selector:
            matchLabels:
              app: prometheus
              environment: development
              owner: naruto
              project: conveyancer
          template:
            metadata:
              labels:
                app: prometheus
                environment: development
                owner: naruto
                project: conveyancer
