apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
  labels: {}
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      version: 25.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 5m0s
  releaseName: prometheus
  uninstall:
    keepHistory: false
  values: {}
  valuesFrom: []
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          version: v1
          kind: Deployment
          name: prometheus
          namespace: default
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: prometheus
        - op: add
          path: /spec/template/metadata/labels/environment
          value: pro
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
      - target:
          version: v1
          kind: Deployment
          name: prometheus-server
          namespace: default
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: prometheus
        - op: add
          path: /spec/template/metadata/labels/environment
          value: pro
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
      - target:
          version: v1
          kind: Deployment
          name: prometheus-prometheus-pushgateway
          namespace: default
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: prometheus
        - op: add
          path: /spec/template/metadata/labels/environment
          value: pro
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
      - target:
          version: v1
          kind: Deployment
          name: prometheus-kube-state-metrics
          namespace: default
        patch:
        - op: add
          path: /spec/template/metadata/labels/app
          value: prometheus
        - op: add
          path: /spec/template/metadata/labels/environment
          value: pro
        - op: add
          path: /spec/template/metadata/labels/project
          value: advanto
        - op: add
          path: /spec/template/metadata/labels/owner
          value: sanujan
