apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-cloudwatch-metrics
  namespace: default
spec:
  chart:
    spec:
      chart: aws-cloudwatch-metrics
      reconcileStrategy: ChartVersion
      version: 0.0.9
      sourceRef:
        kind: HelmRepository
        name: aws
  interval: 5m0s
  releaseName: aws-cloudwatch-metrics
  values:
    affinity: {}
    backend: null
    backends: []
    cache: ""
    certificate:
      create: false
      dnsNames:
      - podinfo
      issuerRef:
        kind: ClusterIssuer
        name: self-signed
    faults:
      delay: false
      error: false
      testFail: false
      testTimeout: false
      unhealthy: false
      unready: false
    h2c:
      enabled: false
    host: null
    hpa:
      cpu: null
      enabled: false
      maxReplicas: 10
      memory: null
      requests: null
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/stefanprodan/podinfo
      tag: 6.5.3
    ingress:
      additionalLabels: {}
      annotations: {}
      className: ""
      enabled: false
      hosts:
      - host: podinfo.local
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls: []
    linkerd:
      profile:
        enabled: false
    logLevel: info
    nodeSelector: {}
    podAnnotations: {}
    probes:
      liveness:
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readiness:
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      startup:
        enable: false
        failureThreshold: 20
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
    redis:
      enabled: false
      repository: redis
      tag: 7.0.7
    replicaCount: 1
    resources:
      limits: null
      requests:
        cpu: 1m
        memory: 16Mi
    securityContext: {}
    service:
      annotations: {}
      enabled: true
      externalPort: 9898
      grpcPort: 9999
      grpcService: podinfo
      hostPort: null
      httpPort: 9898
      metricsPort: 9797
      nodePort: 31198
      type: ClusterIP
    serviceAccount:
      enabled: false
      imagePullSecrets: []
      name: null
    serviceMonitor:
      additionalLabels: {}
      enabled: false
      interval: 15s
    tls:
      certPath: /data/cert
      enabled: false
      hostPort: null
      port: 9899
      secretName: null
    tolerations: []
    ui:
      color: '#34577c'
      logo: ""
      message: ""
  valuesFrom:
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: clusterName
    targetPath: clusterName
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: resources.limits.cpu
    targetPath: resources.limits.cpu
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: resources.limits.memory
    targetPath: resources.limits.memory
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: resources.requests.cpu
    targetPath: resources.requests.cpu
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: resources.requests.memory
    targetPath: resources.requests.memory
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: serviceAccount.create
    targetPath: serviceAccount.create
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: serviceAccount.name
    targetPath: serviceAccount.name
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: statsd.enabled
    targetPath: statsd.enabled
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: statsd.port
    targetPath: statsd.port
  - kind: ConfigMap
    name: aws-cloudwatch-metrics-configmap
    valuesKey: statsd.protocol
    targetPath: statsd.protocol
