apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
  labels:
    app: podinfo
    environment: development
    owner: sanujan
    project: advanto
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      version: 6.5.3
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m0s
  releaseName: podinfo
  values: {}
  valuesFrom: []
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: podinfo
          labels:
            app: podinfo
        spec:
          selector:
            matchLabels:
              app: podinfo
          template:
            metadata:
              labels:
                app: podinfo
                environment: development
                owner: sanujan
                project: advanto
